version: "3.8"

services:
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: fastapi-app
  #    ports:
  #      - "7540:7540"
  #    environment:
  #      - RABBITMQ_HOST=rabbitmq
  #      - RABBITMQ_PORT=5672
  #    depends_on:
  #      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
