apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-service
  namespace: ai-image-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-storage-service
  template:
    metadata:
      labels:
        app: cloud-storage-service
    spec:
      containers:
        - name: cloud-storage-service
          image: aiimageprocacr.azurecr.io/cloud-storage-service:latest
          ports:
            - containerPort: 2660
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-service
  namespace: ai-image-processor
spec:
  selector:
    app: cloud-storage-service
  ports:
    - protocol: TCP
      port: 2660
      targetPort: 2660
  type: ClusterIP
