apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-image-processor-ingress
  namespace: ai-image-processor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host:
      http:
        paths:
          - path: /handler(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: image-handler-service
                port:
                  number: 2740
