spring:
  application:
    name: image-handler-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBITMQ_VHOST:/}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:password}

  datasource:
    url: ${AUTH_SQL_DATASOURCE:jdbc:mysql://localhost:3306/authdb}
    username: ${AUTH_SQL_USERNAME:app_user}
    password: ${AUTH_SQL_PASSWORD:app_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Prevent Hibernate from altering the schema, since Flyway handles migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 2740
  error:
    include-message: always

cloud-storage-service:
  base-url: ${CLOUD_STORAGE_SERVICE:http://localhost:2660}

rabbitmq:
  exchange:
  routing-key: image-processor-task-queue
  queue-name: image-processor-task-queue

jwt:
  secret: ${JWT_SECRET:secret}
  expiration: 86400000 # 24 hours
