apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-handler-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-handler-service
  template:
    metadata:
      labels:
        app: image-handler-service
    spec:
      containers:
        - name: image-handler-service
          image: image-handler-service:latest
          ports:
            - containerPort: 2740
          envFrom:
            - configMapRef:
                name: image-handler-service-config
        - name: nginx-proxy # Nginx container
          image: nginx:latest
          ports:
            - containerPort: 80 # Nginx listens on port 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config # ConfigMap for Nginx config
---
apiVersion: v1
kind: Service
metadata:
  name: image-handler-service
spec:
  selector:
    app: image-handler-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
